services:
  {% if inputs.metrics_tool == 'Prometheus' %}
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml:ro'
  {% elif inputs.metrics_tool == 'AWS CloudWatch' %}
  {{project_name}}:
    environment:
      STACKSPOT_METRICS_CLOUDWATCH_ENDPOINT: 'http://localstack:4566'
    volumes:
      - '~/.aws/config:/root/.aws/config:ro'
      - '~/.aws/credentials:/root/.aws/credentials:ro'

  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
  {% endif %}

networks:
 default:
   driver: bridge
