{% if inputs.metrics_tool == 'Prometheus' %}
scrape_configs:
  - job_name: "{{project_name}}"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
      # - targets: ["172.17.0.1:8080"]  # Replace the above when running on a default Linux Docker
{% endif %}
