name: "metrics-app-kt-plugin"
description: Configure metrics exporting to Prometheus or AWS CloudWatch
types:
  - app
tags:
  - "metrics"
  - "prometheus"
  - "cloudwatch"
inputs:
  - label: "To which tool do you want to export metrics?\n[WARNING] CDK will only be generated for CloudWatch"
    name: "metrics_tool"
    type: text
    default: "AWS CloudWatch"
    items:
      - "AWS CloudWatch"
      - "Prometheus"
hooks:
  - type: edit
    trigger: after-render
    path: infra/src/main/kotlin/{{project_group_id|group_id_folder}}/{{project_name|to_camel}}CdkStack.kt
    changes:
      - search:
          string: 'val accountRole = cluster.addServiceAccount("account", accountOptions).role'
          insert-after:
            value: "{% if inputs.metrics_tool == 'AWS CloudWatch' %}        accountRole.attachInlinePolicy(CloudWatchMetricsPolicy(this, \"cloudwatch-metrics\"))\n{% endif %}"
          when:
            not-exists: 'accountRole.attachInlinePolicy(CloudWatchMetricsPolicy(this, "cloudwatch-metrics"))'
  - type: edit
    trigger: after-render
    path: infra/src/main/kotlin/{{project_group_id|group_id_folder}}/Manifests.kt
    changes:
      - search:
          pattern: 'init\s?{'
          insert-after:
            value: "{% if inputs.metrics_tool == 'AWS CloudWatch' %}        env[\"STACKSPOT_METRICS_CLOUDWATCH_ENDPOINT\"] = EnvValue.fromValue(\"\")\n{% endif %}"
          when:
            not-exists: 'env["STACKSPOT_METRICS_CLOUDWATCH_ENDPOINT"] = EnvValue.fromValue("")'
